/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/chinese-city.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[20, 0, 32]} scale={5}>
        <mesh geometry={nodes.平面035.geometry} material={materials.groud} />
        <mesh geometry={nodes.平面035_1.geometry} material={materials.black} />
        <mesh geometry={nodes.平面035_2.geometry} material={materials.gray} />
        <mesh geometry={nodes.平面035_3.geometry} material={materials.white} />
        <mesh geometry={nodes.平面035_4.geometry} material={materials.grass} />
        <mesh geometry={nodes.平面035_5.geometry} material={materials.rock} />
        <mesh geometry={nodes.平面035_6.geometry} material={materials.leaf} />
        <mesh geometry={nodes.平面035_7.geometry} material={materials['deep wood']} />
        <mesh geometry={nodes.平面035_8.geometry} material={materials.yellow} />
        <mesh geometry={nodes.平面035_9.geometry} material={materials.red} />
        <mesh geometry={nodes.平面035_10.geometry} material={materials.bamboo} />
        <mesh geometry={nodes.平面035_11.geometry} material={materials.dark} />
        <mesh geometry={nodes.平面035_12.geometry} material={materials.iron} />
        <mesh geometry={nodes.平面035_13.geometry} material={materials.water} />
      </group>
    </group>
  )
}

useGLTF.preload('/chinese-city.glb')
