/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/city.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={4.49}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group rotation={[Math.PI / 2, 0, 0]} scale={0.02}>
            <mesh geometry={nodes.Object_0.geometry} material={materials.Meshpart1Mtl} />
            <mesh geometry={nodes.Object_0_1.geometry} material={materials.Meshpart2Mtl} />
            <mesh geometry={nodes.Object_0_2.geometry} material={materials.Meshpart3Mtl} />
            <mesh geometry={nodes.Object_0_3.geometry} material={materials.Meshpart4Mtl} />
            <mesh geometry={nodes.Object_0_4.geometry} material={materials.Meshpart5Mtl} />
            <mesh geometry={nodes.Object_0_5.geometry} material={materials.Meshpart6Mtl} />
            <mesh geometry={nodes.Object_0_6.geometry} material={materials.Meshpart7Mtl} />
            <mesh geometry={nodes.Object_0_7.geometry} material={materials.Meshpart8Mtl} />
            <mesh geometry={nodes.Object_0_8.geometry} material={materials.Meshpart9Mtl} />
            <mesh geometry={nodes.Object_0_9.geometry} material={materials.Meshpart11Mtl} />
            <mesh geometry={nodes.Object_0_10.geometry} material={materials.Meshpart12Mtl} />
            <mesh geometry={nodes.Object_0_11.geometry} material={materials.Meshpart13Mtl} />
            <mesh geometry={nodes.Object_0_12.geometry} material={materials.Meshpart14Mtl} />
            <mesh geometry={nodes.Object_0_13.geometry} material={materials.Meshpart15Mtl} />
            <mesh geometry={nodes.Object_0_14.geometry} material={materials.Meshpart16Mtl} />
            <mesh geometry={nodes.Object_0_15.geometry} material={materials.Meshpart17Mtl} />
            <mesh geometry={nodes.Object_0_16.geometry} material={materials.Meshpart18Mtl} />
            <mesh geometry={nodes.Object_0_17.geometry} material={materials.Meshpart19Mtl} />
            <mesh geometry={nodes.Object_0_18.geometry} material={materials.Meshpart20Mtl} />
            <mesh geometry={nodes.Object_0_19.geometry} material={materials.Meshpart21Mtl} />
            <mesh geometry={nodes.Object_0_20.geometry} material={materials.Meshpart22Mtl} />
            <mesh geometry={nodes.Object_0_21.geometry} material={materials.Meshpart23Mtl} />
            <mesh geometry={nodes.Object_0_22.geometry} material={materials.Meshpart24Mtl} />
            <mesh geometry={nodes.Object_0_23.geometry} material={materials.Meshpart26Mtl} />
            <mesh geometry={nodes.Object_0_24.geometry} material={materials.Meshpart27Mtl} />
            <mesh geometry={nodes.Object_0_25.geometry} material={materials.Meshpart28Mtl} />
            <mesh geometry={nodes.Object_0_26.geometry} material={materials.Meshpart30Mtl} />
            <mesh geometry={nodes.Object_0_27.geometry} material={materials.Meshpart32Mtl} />
            <mesh geometry={nodes.Object_0_28.geometry} material={materials.Meshpart35Mtl} />
            <mesh geometry={nodes.Object_0_29.geometry} material={materials.Meshpart36Mtl} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/city.glb')
