/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/monkey.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Suzanne.geometry} material={materials.Gold} />
      <mesh geometry={nodes.Suzanne001.geometry} material={materials.Silver} position={[-3.06, 0.03, 0.23]} />
      <mesh geometry={nodes.Suzanne002.geometry} material={materials.Copper} position={[2.61, -0.51, -0.93]} />
    </group>
  )
}

useGLTF.preload('/monkey.glb')
