/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.7 .\public\models\obstacleCourse.glb -d
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/obstacleCourse.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cube.geometry} material={materials['Material.001']} />
      <mesh geometry={nodes.Cube001.geometry} material={materials['Material.001']} position={[5.197, 1.002, -6.42]} scale={[0.597, 0.091, 1]} />
      <mesh geometry={nodes.Cube002.geometry} material={materials['Material.001']} position={[-0.013, 1.002, -6.42]} scale={[3.04, 0.091, 0.128]} />
      <mesh geometry={nodes.Cube003.geometry} material={materials['Material.001']} position={[-4.803, 1.936, -4.561]} rotation={[-0.447, 0, 0]} scale={[0.597, 0.077, 2.726]} />
      <mesh geometry={nodes.Cube004.geometry} material={materials['Material.001']} position={[-4.875, 3.025, 0.845]} scale={[2.289, 0.091, 2.208]} />
    </group>
  )
}

useGLTF.preload('/obstacleCourse.glb')
