/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/sh3d-test.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.HomeIdea3D.geometry} material={materials['Default OBJ']} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.floor2.geometry} material={materials['Default OBJ']} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.floor3.geometry} material={materials['Default OBJ']} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
    </group>
  )
}

useGLTF.preload('/sh3d-test.glb')
