/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

// Initially created using this command
// npx gltfjsx ..\public\models\shoe-draco.glb -r ./src

import React, { useRef } from 'react'
import { useFrame } from '@react-three/fiber'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const ref = useRef()
  useFrame((state) => {
    const t = state.clock.getElapsedTime()
    //ref.current.rotation.z =Math.sin(t) //tilt
    ref.current.rotation.x = Math.cos(t / 4) / 2 // tilt left @ right
    //ref.current.rotation.y = Math.sin(t) //swing left & right
    //ref.current.position.y = (1 + Math.sin(t / 1.5)) / 10
  })

  const { nodes, materials } = useGLTF('./models/shoe-draco.glb')
  return (
    <group ref={ref} {...props} dispose={null} onPointerOver={(e) => console.log(e.object.material.name)}>
      <mesh geometry={nodes.shoe.geometry} material={materials.laces} />
      <mesh geometry={nodes.shoe_1.geometry} material={materials.mesh} />
      <mesh geometry={nodes.shoe_2.geometry} material={materials.caps} />
      <mesh geometry={nodes.shoe_3.geometry} material={materials.inner} />
      <mesh geometry={nodes.shoe_4.geometry} material={materials.sole} />
      <mesh geometry={nodes.shoe_5.geometry} material={materials.stripes} />
      <mesh geometry={nodes.shoe_6.geometry} material={materials.band} />
      <mesh geometry={nodes.shoe_7.geometry} material={materials.patch} />
    </group>
  )
}

useGLTF.preload('./models/shoe-draco.glb')
